Turret anchoring fix
DS-13-Dev-Team/DS13-1.0 pull request #1038
Opened 2020-12-03 09:56 UTC by JeserTheFox

bugfix: "Fixed being able to unsecure buildable turrets."

New "portable" var decides whether turret can be unsecured or not,

2020-12-04 15:45 UTC, NanakoAC requested changes
one tiny fix

2020-12-04 15:45 UTC, NanakoAC commented on code/game/machinery/turret/turret.dm
> +				to_chat(user, "<span class='warning'>This turrent cannot be unsecured.</span>")
typo here, should be turret

2020-12-05 07:07 UTC, JeserTheFox commented on code/game/machinery/turret/turret.dm
> +				to_chat(user, "<span class='warning'>This turrent cannot be unsecured.</span>")
Typo fixed.

2020-12-07 17:01 UTC, NanakoAC approved these changes

2020-12-15 00:32 UTC, merged