Pop-up text on mob.
DS-13-Dev-Team/DS13-1.0 pull request #1066
Opened 2021-01-02 23:32 UTC by DeadLineSS13

Add pop-up text on mob.
![unknown](https://user-images.githubusercontent.com/41364830/103468592-d37dab80-4d6b-11eb-8178-4385713d9794.png)

2021-01-05 10:14 UTC, NanakoAC requested changes
Alright, after testing it out, i've noted a few small problems:
1. It's not enabled by default, most people will never notice it without that, turn it on.
2. The line spacing between the text is a bit much, easy to make big towers, try reducing that
3. The time that it stays onscreen is too short, barely time to read it. Increase by 50%
4. Radio messages are shown there too. Generally, they should only be shown to people who were close enough to hear the message

2021-01-07 18:03 UTC, JakeDaBoss commented
Besides what Nanako put up, did you confirm that Humans cannot see Necro's pop-ups, or does it happen for them at all?

2021-01-07 18:16 UTC, DeadLineSS13 commented
> Besides what Nanako put up, did you confirm that Humans cannot see Necro's pop-ups, or does it happen for them at all?

Nanako check this.

2021-01-14 20:48 UTC, NanakoAC commented on code/modules/mob/living/say.dm
> +				if(M.client)
hear_say also includes a check for client so this one is unnecessary

2021-01-14 20:53 UTC, NanakoAC approved these changes

2021-01-14 20:56 UTC, merged