Javelin Gun
DS-13-Dev-Team/DS13-1.0 pull request #1302
Opened 2021-02-26 22:23 UTC by Evankhell561

It is a weapon that embeds projectiles in its victims so that the user can then exploit them to electrocute the victim
:cl:
add: Javelin Gun
/:cl:

2021-03-18 15:55 UTC, NanakoAC requested changes
This is a very rough draft which unfortunately leaves a lot to be desired.

The firing sound is way wrong, even for a placeholder it doesn't make sense, try to look for a bettter one. crossbow or pneumatic launcher perhaps

this doesn't make sense
https://i.imgur.com/CuwzGQz.png
A javelin is a spear, this is like saying knife sword. there's only one so no plurality is needed either

We have good sounds for things sticking into flesh, look at the unitology ritual blade and apply such sounds to the javelin embedding

The electrocution effect is supposed to be an AOE spray of lightning for several seconds, not just a couple of sparks. We have no custom sprites for this, and I was hoping you'd come up with something to improvise.  See what you can do with tesla sprite effects, otherwise we'll have to wait on more assets

Its supposed to continue for about 4 seonds, OR until the user lets go of the fire button. Being able to hold it down for extra crispiness is cathartically important

The detonation mode also frequently just doesn't work at all, not sure what's going on there

Also the detonation mode should consume a javelin (from the gun) to use. Counterintuitive I know, but its a game balance thing.

Lastly, the nailing effect is completely missing. On anything human sized, the javelin gun will launch them flying, and pin them to any walls they hit. Use push impulse for the launching, set a bump observation to watch for the victim hitting viable obstacles (walls mostly) and look at powered crossbow for how to pin someone to a wall

On a technical level it would probably also make sense not to implant the javelin into the victim's body, but have it as a seperate object on the turf. that'll make it easier to render and allow others to grab it to help pull it out

2021-03-26 01:49 UTC, Evankhell561 commented
![image](https://user-images.githubusercontent.com/49106866/112565686-cd80ef00-8ddd-11eb-8d99-08aa0e196789.png)

![image](https://user-images.githubusercontent.com/49106866/112565686-cd80ef00-8ddd-11eb-8d99-08aa0e196789.png)

2021-04-04 08:29 UTC, NanakoAC commented
comments from functional testing:
The push effect is still missing. The javelin gun hits the target with enough force to launch them away, and pins them to any walls they hit in flight.  Use push impulse for this, check impulse.dm, and pin them if they're still flying when they hit a wall

The lightning effect sort of works, you got the controls right, but the functional effect of it is pretty minimal. I put a few slashers together and was unable to hurt either of them (epicentre or a nearby tile) with the electricity. Walking through it myself, i only took about 10 burn damage, it needs to be wayyyy stronger than this. For a guide on power, a javelin through the chest, and then a full discharge of electricity, should easily be enough to kill any T1 necromorph, and severely injure a T2. See if you can tweak the power to achieve these goals

Dropping an ammo casing on the floor doesn't exactly make sense. Having an object on the turf is a good idea if the victim gets pinned, in which case it should be mounted to the wall (see wallmount.dm), as well as rotated and offset to point into that wall. if the victim is too big to pin to anything, just embedding would be fine, in that case it doesn't make sense to leave an object behind outside of the target's body. 
since you've got two use cases here it may be best to make an extension to handle creating the electricity damage


Aside from the above, the audio is still not great. we don't have proper audio for it yet but there are definitely better placeholders, use the crossbow sound effects

2021-04-18 02:04 UTC, NanakoAC requested changes
first phase of review from code reading, some changes needed.

now going to do practical testing

2021-04-18 02:04 UTC, NanakoAC commented on code/game/atoms.dm
> +/atom/proc/register_sharpnel(obj/item/weapon/material/shard/shrapnel/SP)
this is pronounced shrapnel

2021-04-18 02:04 UTC, NanakoAC commented on code/game/objects/items/weapons/material/shards.dm
> +	icon_state = "SpearFlight"
its generally bad form to use capital letters in things like this

2021-04-18 02:04 UTC, NanakoAC commented on code/game/objects/items/weapons/material/shards.dm
> +	name = "javeling"
there's no g in javelin

2021-04-18 02:04 UTC, NanakoAC commented on code/game/objects/items/weapons/material/shards.dm
> +/obj/item/weapon/material/shard/shrapnel/javeling/proc/remove_from_luncher_list()
launcher not luncher

2021-04-18 02:04 UTC, NanakoAC commented on code/modules/projectiles/guns/projectile/javelin.dm
> +		J.detone_javelin(user)
detonate javelin

2021-04-18 02:04 UTC, NanakoAC commented on code/modules/projectiles/guns/projectile/javelin.dm
> +	START_PROCESSING(SSobj, src)
This is too slow, use SSfastprocess instead, and break the damage down over 0.2 sec increments

2021-04-18 02:04 UTC, NanakoAC commented on code/modules/projectiles/projectile/bullets.dm
> +	armor_penetration = 50
make this 15

2021-04-18 02:04 UTC, NanakoAC commented on code/modules/projectiles/projectile/bullets.dm
> +	damage = 20
30 damage

2021-04-18 02:55 UTC, Evankhell561 commented on code/modules/projectiles/projectile/bullets.dm
> +	armor_penetration = 50
```suggestion
	armor_penetration = 15
```

2021-04-18 02:55 UTC, Evankhell561 commented on code/modules/projectiles/projectile/bullets.dm
> +	damage = 20
```suggestion
	damage = 30
```

2021-04-18 18:00 UTC, NanakoAC commented
Forgot to unregister from the new system

`[13:01:29] Runtime in unsorted.dm,1071: Failed to stop processing. The overload (/obj/effect/overload) ([0x2032f3b]) (the deck) (210,139,4) (/turf/simulated/floor/tiled/dark) is being processed by SSfastprocess but de-queue attempt occured on SSobj.
  proc name: crash with (/proc/crash_with)
  src: null
  call stack:
  crash with("Failed to stop processing. The...")
  the overload (/obj/effect/overload): Destroy(0)
  qdel(the overload (/obj/effect/overload), 0)
  the overload (/obj/effect/overload): Process(2, 436, Fast Processing (/datum/controller/subsystem/processing/fastprocess))
  Fast Processing (/datum/controller/subsystem/processing/fastprocess): fire(0)
  Fast Processing (/datum/controller/subsystem/processing/fastprocess): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)`

2021-04-18 18:05 UTC, Evankhell561 commented
> Forgot to unregister from the new system
> 
> `[13:01:29] Runtime in unsorted.dm,1071: Failed to stop processing. The overload (/obj/effect/overload) ([0x2032f3b]) (the deck) (210,139,4) (/turf/simulated/floor/tiled/dark) is being processed by SSfastprocess but de-queue attempt occured on SSobj. proc name: crash with (/proc/crash_with) src: null call stack: crash with("Failed to stop processing. The...") the overload (/obj/effect/overload): Destroy(0) qdel(the overload (/obj/effect/overload), 0) the overload (/obj/effect/overload): Process(2, 436, Fast Processing (/datum/controller/subsystem/processing/fastprocess)) Fast Processing (/datum/controller/subsystem/processing/fastprocess): fire(0) Fast Processing (/datum/controller/subsystem/processing/fastprocess): ignite(0) Master (/datum/controller/master): RunQueue() Master (/datum/controller/master): Loop() Master (/datum/controller/master): StartProcessing(0)`

sorry

2021-04-18 18:05 UTC, NanakoAC commented
The accuracy is pretty bad, crank that up and set dispersion to 0 as well

2021-04-18 18:08 UTC, NanakoAC commented
Freeing the victim from the pinning works, but its instant and throws a runtime error. 

It ought to have a do-after and take a few seconds, twice as long if the victim is trying to free themselves
`## ERROR: Cannot read null.extensions - extensions.dm - 108
## ERROR: proc name: remove extension (/proc/remove_extension)
  source file: extensions.dm,108
  usr: Bluespace Technician (/mob/living/carbon/human/bst)
  src: null
  usr.loc: the deck (211,138,4) (/turf/simulated/floor/tiled/dark)
  call stack:
remove extension(null, Mount (/datum/extension/mount/self_delete))
Mount (/datum/extension/mount/self_delete): dismount()
Mount (/datum/extension/mount/self_delete): mountpoint updated()
Mount (/datum/extension/mount/self_delete): on mountee move(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), the deck (211,139,4) (/turf/simulated/floor/tiled/dark), Bluespace Technician (/mob/living/carbon/human/bst))
Moved (/decl/observ/moved): raise event(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), the deck (211,139,4) (/turf/simulated/floor/tiled/dark), Bluespace Technician (/mob/living/carbon/human/bst))
Bluespace Technician (/mob/living/carbon/human/bst): Entered(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), the deck (211,139,4) (/turf/simulated/floor/tiled/dark))
Bluespace Technician (/mob/living/carbon/human/bst): Entered(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), the deck (211,139,4) (/turf/simulated/floor/tiled/dark))
Bluespace Technician (/mob/living/carbon/human/bst): Entered(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), the deck (211,139,4) (/turf/simulated/floor/tiled/dark))
the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling): forceMove(Bluespace Technician (/mob/living/carbon/human/bst))
the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling): forceMove(Bluespace Technician (/mob/living/carbon/human/bst))
...
Bluespace Technician (/mob/living/carbon/human/bst): equip to slot(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), 5, 1)
Bluespace Technician (/mob/living/carbon/human/bst): put in r hand(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling))
Bluespace Technician (/mob/living/carbon/human/bst): put in active hand(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling))
the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling): attack hand(Bluespace Technician (/mob/living/carbon/human/bst))
Bluespace Technician (/mob/living/carbon/human/bst): UnarmedAttack(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), 1)
Bluespace Technician (/mob/living/carbon/human/bst): LeftClickOn(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), "icon-x=75;icon-y=8;left=1")
Bluespace Technician (/mob/living/carbon/human/bst): ClickOn(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), "icon-x=75;icon-y=8;left=1")
the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling): Click("Turf", "infowindow.info", "icon-x=75;icon-y=8;left=1")
NanakoAC (/client): Click(the steel shrapnel (/obj/item/weapon/material/shard/shrapnel/javeling), "Turf", "infowindow.info", "icon-x=75;icon-y=8;left=1")
`

Also the push force on the impact is a bit lacking, can't really pin a slasher unless they're already next to the wall.
Crank it up majorly, a clean hit should launch a slasher across the room, and allow them to hit a wall about 5 tiles away

Feel free to adjust necromorph weights and push falloff code if necessary to make this work

2021-04-18 18:08 UTC, NanakoAC commented
the audio placeholders are still bad, i'll try to get the right sounds from resident

2021-04-18 19:28 UTC, NanakoAC commented
ah one more thing,
make the push force be halved if the victim is hit in a non-torso location. this is one weapon you want to aim centre mass with

2021-04-18 20:01 UTC, NanakoAC commented
And throw this sound in whenever the javelin embeds/pins a victim, and when its pulled out:

`playsound(src, "fleshtear", VOLUME_MID, TRUE)`

2021-05-16 00:14 UTC, NanakoAC commented
superceded by #1426

2021-05-16 00:14 UTC, closed without merging