fix Runtime in ghost.dm, line 57: Cannot modify null.ghost.
DS-13-Dev-Team/DS13-1.0 pull request #1332
Opened 2021-03-21 21:47 UTC by Evankhell561

fix: #1328

2021-03-27 22:16 UTC, NanakoAC approved these changes

2021-03-27 22:17 UTC, NanakoAC requested changes
I don't understand what you're doing here, using spawns is awful and should be avoided

2021-03-31 20:46 UTC, Evankhell561 commented
> I don't understand what you're doing here, using spawns is awful and should be avoided

I used spawn because it is the same code that is already used below in that dm.
![image](https://user-images.githubusercontent.com/49106866/113209137-f4727180-9272-11eb-9c28-6f4fd5f87667.png)

2021-04-10 17:04 UTC, NanakoAC approved these changes

2021-04-14 17:55 UTC, merged