Slasher clothing: captain edition
DS-13-Dev-Team/DS13-1.0 pull request #1360
Opened 2021-04-11 03:51 UTC by Evankhell561

:cl:
add: the captain's uniform now has a sprite when equipped by a Slasher.
add: now you can give the slasher some uniforms.
/:cl:

2021-04-11 03:54 UTC, Evankhell561 commented
![image](https://user-images.githubusercontent.com/49106866/114291790-19779900-9a58-11eb-9196-047660b2965f.png)
![image](https://user-images.githubusercontent.com/49106866/114291792-1da3b680-9a58-11eb-941b-49e6a2d05e85.png)
![image](https://user-images.githubusercontent.com/49106866/114291795-22686a80-9a58-11eb-96cb-d9263808aa44.png)

2021-04-13 12:33 UTC, NanakoAC requested changes
one change, see comments

Also what about the mining and engineering rig sprites, will you be implementing those seperately?

2021-04-13 12:33 UTC, NanakoAC commented on code/__defines/species.dm
> +#define SPECIES_ALL_NECROMORPHS_NO_SLASHERS SPECIES_NECROMORPH,\
this is unnecessary, species restrictions are handled at runtime in necro outfits

2021-04-14 21:37 UTC, NanakoAC approved these changes

2021-04-14 22:06 UTC, merged