Necromorphs will no longer speak english
DS-13-Dev-Team/DS13-1.0 pull request #1468
Opened 2021-06-08 19:28 UTC by DTraitor

### Purpose
Necromorphs will no longer speak english
Fixes: #1336

2021-06-08 21:23 UTC, NanakoAC requested changes

2021-06-08 21:23 UTC, NanakoAC commented on code/modules/mob/living/carbon/human/species/necromorph/necromorph_species.dm
> +	default_language = "Signal Hivemind"
don't use string literals when a define exists, stick with that

why not set it in both vars too?

2021-06-09 11:04 UTC, DTraitor commented on code/modules/mob/living/carbon/human/species/necromorph/necromorph_species.dm
> +	default_language = "Signal Hivemind"
**#define** doesnt work in this case and the game can't find language to use so it automatically sets it to english common. Var is declared in **species.dm**.

_P.S. Monkeys use the same code as I put here_

2021-06-09 15:26 UTC, DTraitor commented
whoops, merged to wrong branch

2021-06-09 20:22 UTC, NanakoAC commented on code/modules/mob/living/carbon/human/species/necromorph/necromorph_species.dm
> +	default_language = "Signal Hivemind"
well that definitely doesn't make sense. Perhaps the define is mis-spelled, try looking into it

2021-06-11 15:45 UTC, DTraitor commented
Closing this because I couldn't find a way to use **#define** in this case (it doesnt work because it requires var in **say.dm**), **var/language** is declared in **species.dm** and changing it using simple "language = null "doesnt arranges @NanakoAC.

2021-06-11 15:45 UTC, closed without merging