Hydrazine torch fires in vacuum again
DS-13-Dev-Team/DS13-1.0 pull request #1883
Opened 2021-10-16 12:49 UTC by DTraitor

### Purpose
Fixes: https://github.com/DS-13-Dev-Team/DS13/issues/1856

2021-10-16 17:16 UTC, Ketrai commented
Make sure it's only for hydrazine fuel though. Not regular fuel.

2021-10-16 20:18 UTC, NanakoAC commented on code/modules/projectiles/guns/ds13/flamethrower.dm
> -	vacuum_burn = FALSE
i don't see how this would help. The same logic still applies doesn't it?

2021-10-16 20:18 UTC, NanakoAC commented on code/modules/projectiles/guns/ds13/flamethrower.dm
> +	vacuum_burn = TRUE
this shouldn't be necessary as the fuel updating proc handles it. If there's a situation where its not being called, find that and put in a call

2021-10-18 01:21 UTC, NanakoAC requested changes
After discussion in dev closet, the recommended solution here is as follows:

Either Add a new gun proc to create the initial ammo, or make the process of creating initial ammo call something (ammo inserted?) that is also called when a magazine/tank/bullet/etc is inserted normally

Override that proc to make the hydrazine torch update its fuel when it recieves a new tank

2021-10-21 07:36 UTC, NanakoAC approved these changes
lets just get this merged

2021-10-22 00:19 UTC, merged