medical rig update
DS-13-Dev-Team/DS13-1.0 pull request #2153
Opened 2022-08-26 02:50 UTC by nianoru

sprite changes

2022-08-26 02:53 UTC, nianoru commented
The commits above are simply visual/sprite changes. In-game implementation will be put in Viz's PR, as he decided to go forth and do it to prevent conflict.

2022-08-26 05:00 UTC, nianoru commented
ready for review

2022-08-26 08:11 UTC, nianoru commented
for the medical rig commit, it's simply visual/sprite changes. In-game implementation will be put in Viz's PR, as he decided to go forth and do it to prevent conflict. This PR is ready for review.

2022-08-26 11:59 UTC, DTraitor requested changes
Just some small tweaks. Remove `medical_rig_old` sprites, if we ever need old sprites we will use github commit history. HUD sprite of the RIG in `icons/obj/rig_frames.dm` should be `Back_in_inv.png`, not a bike horn sprite.

2022-08-26 11:59 UTC, DTraitor commented on code/modules/clothing/spacesuits/rig/suits/civilian.dm
> +	desc = "honk honk."
Description should start with a capital letter

2022-09-03 10:56 UTC, DTraitor approved these changes

2022-09-04 08:27 UTC, nianoru commented
Not sure if Viz left a changelog of his own in code. If you need me to add it into this PR before closing it, let me know via discord or here.

2022-09-08 06:21 UTC, nianoru commented
Adding store kiosk/supply management revamp before this friday! :)

2022-09-08 20:23 UTC, nianoru commented
PR finished.

2022-09-09 08:52 UTC, nianoru commented
the last 3 shoulda been one commit, had a troll moment. anyways.. PR is finished woo.

2022-09-09 08:57 UTC, nianoru commented
the last 3 shoulda been one commit, had a troll moment and its also 5am. anyways.. PR is finished woo.. :')

2022-09-09 12:15 UTC, DTraitor approved these changes

2022-09-10 23:50 UTC, merged