Reduces the volume of salt in salt sacks
DS-13-Dev-Team/DS13-1.0 pull request #2196
Opened 2022-10-15 08:57 UTC by githubuser4141

What this PR Does & Why:

Simply put, it reduces the amount of salt found in the large salt containers in spawn lockers to 50 units, from 500, and adds a warning note.

Why? 'Cause dying from excessive salt consumption isn't fun, and, there's really no reason for such a huge amount of salt to exist round start. It makes ordering salt from Supply pointless as there's enough salt in each bag to last the entire shift even if you're an active cook.

2022-10-15 13:27 UTC, DTraitor requested changes
Just one tweak

2022-10-15 13:27 UTC, DTraitor commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +				y soy-based flavoring."
revert this changes

2022-10-15 22:47 UTC, githubuser4141 commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +				y soy-based flavoring."
Fixed.

2022-10-17 18:17 UTC, DTraitor approved these changes

2022-10-23 23:53 UTC, Vizoplez commented
People on their way not to realise 1u of potassium and 1u of water instantly clears your bloodstream and stomach......

shaking my fucking head right now

2022-10-27 15:25 UTC, merged