Trollge
DS-13-Dev-Team/DS13-1.0 pull request #2200
Opened 2022-10-23 14:49 UTC by Yawet330

This makes xenoarch FAR more dangerous and helps prevent future atmos grief with it.

2022-10-23 15:57 UTC, Vizoplez commented
Essentially this PR
-Buffs the chance of LARGE artifacts spawning
-Makes them more likely to activate on being discovered (thus performing their effect)
-Removes the atmospheric grief effects (such as spawning phoron/plasma)
-Removes the requirement to change the atmosphere to cause them to activate (as this can be construed as potentially breaking server rules, especially on the Ishi where an artifact that suddenly heats the atmosphere to 9000c is bad)

2022-10-31 18:11 UTC, DTraitor requested changes
Just one tweak, otherwise good

2022-10-31 18:11 UTC, DTraitor commented on code/modules/xenoarcheaology/effects/radiate.dm
> +	radiation_strength = rand(50, 150) //You're GOING to die VERY fast without immediate medical attention
Lets not make radiation too powerful, Lets keep it to something like rand(20, 70)

2022-11-05 02:39 UTC, Ketrai commented
I am still concerned with how frequent artefacts spawn now as that's a lot of free materials for science to abuse. I see a lot more material sheet spawns...

2022-11-30 01:50 UTC, closed without merging