Discord Verb
DS-13-Dev-Team/DS13-1.0 pull request #550
Opened 2020-07-22 18:41 UTC by JakeDaBoss

Adds a "Join the Discord" OOC Verb.

2020-07-22 18:42 UTC, NanakoAC commented on code/controllers/configuration.dm
> +				if("law_zero")
this seems out of place

2020-07-22 18:42 UTC, NanakoAC requested changes
one oddity

2020-07-22 19:28 UTC, NanakoAC approved these changes

2020-07-24 12:24 UTC, JakeDaBoss commented on config/example/config.txt
> +## Discord URL - Used for the "Join the Discord" verb in OOC.
@WestHybrid You'll need to pay special mind to this, for when you merge. You'll have to add this to the existing config.

2020-07-25 17:34 UTC, merged