Allows Security RIGs to take Modular Armour attachments
DS-13-Dev-Team/DS13-1.0 pull request #569
Opened 2020-07-29 22:49 UTC by 5crownik007

Allows security rig chestplate to take attachments from the modular armour system. ONLY insignia, armour tags and storage pouches are allowed.

2020-07-30 06:28 UTC, JakeDaBoss requested changes
Please change the changelog name to 5crownik007-PR-569.

This is our currently accepted format.

2020-07-30 12:01 UTC, 5crownik007 commented
> 
> 
> Please change the changelog name to 5crownik007-PR-569.
> 
> This is our currently accepted format.

Done

2020-08-01 03:38 UTC, JakeDaBoss approved these changes
No structural errors and all good. As far as the idea goes, that's up to Snype and West.

2020-08-01 15:14 UTC, NanakoAC approved these changes

2020-08-03 05:00 UTC, merged